### ISSUE TITLE
insted of repl.it

### ISSUE THREAD

**Issue by YamatoGit** [Mewzax/Discord-RPC-Selfbot#11]
we could just host it by using cmd since its safe i guess

**Comment by YamatoGit** [comment]
also got an error
`node:546) UnhandledPromiseRejectionWarning: RpcError: '' n'est pas un string.
    at Object.getRpcImage (/home/runner/Discord-RPC-Selfbot/node_modules/discordrpcgenerator/index.js:1:8158)
    at Client.<anonymous> (/home/runner/Discord-RPC-Selfbot/presences/game.js:9:17)
    at Client.emit (events.js:326:22)
    at WebSocketConnection.triggerReady (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:141:61)
    at ReadyHandler.handle (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/handlers/Ready.js:79:8)
    at WebSocketPacketManager.handle (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/Discord-RPC-Selfbot/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/runner/Discord-RPC-Selfbot/node_modules/ws/lib/event-target.js:120:16)
(node:546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by Mewzax** [comment]
Problem with rpc image can u send me config

**Comment by YamatoGit** [comment]
fixed the issue but using node in cmd doesnt
C:\Users\Admin\Documents\BasicScripts\Discord-RPC-Selfbot-main\index.js:9
  throw new Error('No token specified, please set TOKEN environment variable');


Error: No token specified, please set TOKEN environment variable
    at Object.<anonymous> (C:\Users\Admin\Documents\BasicScripts\Discord-RPC-Selfbot-main\index.js:9:9)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

**Comment by Mewzax** [comment]
> fixed the issue but using node in cmd doesnt C:\Users\Admin\Documents\BasicScripts\Discord-RPC-Selfbot-main\index.js:9 throw new Error('No token specified, please set TOKEN environment variable');
> 
> Error: No token specified, please set TOKEN environment variable at Object. (C:\Users\Admin\Documents\BasicScripts\Discord-RPC-Selfbot-main\index.js:9:9) ←[90m at Module._compile (node:internal/modules/cjs/loader:1103:14)←[39m ←[90m at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)←[39m ←[90m at Module.load (node:internal/modules/cjs/loader:981:32)←[39m ←[90m at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m ←[90m at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m ←[90m at node:internal/main/run_main_module:17:47←[39m

Edit code and replace all the port on process.env with just your token
