### ISSUE TITLE
RPC crashes on replit

### ISSUE THREAD

**Issue by sneazy-ibo** [Mewzax/Discord-RPC-Selfbot#14]
My replit project stops running after like one hour, altough I hosted it on uptimerobot. Even after the rpc crashes, uptimerobot says it's up. This is the error that I get everytime:
```
/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/actions/MessageCreate.js:31
        const message = channel._cacheMessage(new Message(channel, data, client));
                                ^

TypeError: channel._cacheMessage is not a function
    at MessageCreateAction.handle (/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/actions/MessageCreate.js:31:33)
    at MessageCreateHandler.handle (/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/handlers/MessageCreate.js:8:51)
    at WebSocketPacketManager.handle (/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/Discord-RPC/node_modules/discord.js-selfbot-v11/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/runner/Discord-RPC/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/Discord-RPC/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/runner/Discord-RPC/node_modules/ws/lib/receiver.js:422:14)
exit status 1
```

**Comment by Mewzax** [comment]
Uhhhh error with discord.js module try using another

**Comment by sneazy-ibo** [comment]
> Uhhhh error with discord.js module try using another 

Wdym with using another module, sry but Ion know node js and don't have much experience with coding

**Comment by Mewzax** [comment]
Instead of using discord.js-selfbot-v11 (its in require() and package.json use another module for selfbots you can try to find it on github
