### ISSUE TITLE
s.find is not a function

### ISSUE THREAD

**Issue by HoriKyoukosimp** [mewzax/Discord-RPC-Selfbot#25]
```
TypeError: s.find is not a function
    at Object.getRpcImage (/home/ubuntu/Discord-RPC-Selfbot/node_modules/discordrpcgenerator/index.js:1:8216)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getImage (/home/ubuntu/Discord-RPC-Selfbot/utils/discord.js:3:52)
    at async Client.<anonymous> (/home/ubuntu/Discord-RPC-Selfbot/presences/game.js:17:46)

Node.js v20.8.0
```

idk what i do wrong but sometimes it launch successfully (idk whats happening with getRpcImages, the discord developer art assets tab is buggy as hell)

**Comment by HoriKyoukosimp** [comment]
https://cdn.anisp.xyz/dVy78Bq4Znpo.png

it now launch

buh

**Comment by AgielGomes** [comment]
How did you make it work? For me it only discord rpc message shows up, but does not log in (on my python selfbot it logs fine, so its not a token problem). After some time it crashes for tooking too long to do something
